# TOML configuration file for vid-cleaner

# Languages to keep (list of ISO 639-1 codes)
keep_languages = ["en"]

# External services used to determine the original language of a movie or TV show
radarr_api_key = ""
radarr_url     = ""
sonarr_api_key = ""
sonarr_url     = ""
tmdb_api_key   = ""
