---
name: "Upload to Codecov"

on:
    workflow_dispatch:
    workflow_run:
        workflows: ["Automated Tests"]
        types:
            - completed
        branches:
            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    upload-coverage:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        strategy:
            fail-fast: true
            matrix:
                python-version: ["3.11"]
        steps:
            - name: Harden Security Runner
              uses: step-security/harden-runner@v2
              with:
                  egress-policy: block
                  disable-sudo: true
                  allowed-endpoints: >
                      api.github.com:443 api.snapcraft.io:443 auth.docker.io:443 codecov.io:443 files.pythonhosted.org:443 github.com:443 production.cloudflare.docker.com:443 pypi.org:443  registry-1.docker.io:443 storage.googleapis.com:443 *.codecov.io:443 astral.sh:443 objects.githubusercontent.com:443


            - name: Checkout repository
              uses: actions/checkout@v4

            # ----------------------------------------------
            # Setup Python, uv, and install project dependencies
            # ----------------------------------------------

            - name: Setup Python, uv, and the package
              uses: ./.github/actions/uv-python-package

            # ----------------------------------------------
            # Run tests
            # ----------------------------------------------

            - name: Run tests with pytest
              run: |
                  uv run coverage run
                  uv run coverage report
                  uv run coverage xml
            # ----------------------------------------------
            #             upload coverage stats
            # ----------------------------------------------
            - name: Upload coverage
              uses: codecov/codecov-action@v4
              with:
                  files: reports/coverage.xml
              env:
                  CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

            # ----------------------------------------------
            # Cleanup cache
            # ----------------------------------------------

            - name: Minimize uv cache
              shell: bash
              run: uv cache prune --ci

    on-failure:
        runs-on: ubuntu-latest
        if: ${{ github.event.workflow_run.conclusion == 'failure' }}
        steps:
            - run: echo 'The triggering workflow failed'
